sudo: false
language: python
addons:
  firefox: latest

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=functional
    - python: 3.7
      env: TOXENV=lint


before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - tests/get_linux64_geckodriver.sh
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

install:
  - pip install tox

script:
  - tox
